### ISSUE TITLE
Can this model be trained as well? 

### ISSUE THREAD

**Issue by mosheliv** [qubvel/efficientnet#1]
Or only inference?

**Comment by ECOFRI** [comment]
I’m now training the b7 network without imagenet pretrained weights, but it couldn’t be well trained. I changed some optimizer settings, but does not work well.

Is there anyone who can share optimizer settings?

**Comment by qubvel** [comment]
There is some uncertainty about `drop_connect_rate`. It should be much lower at the first blocks. Currently I am waiting answer for issue, and the will fix it.

**Comment by ECOFRI** [comment]
With my personal dataset:

Training with Inception v3 -> well working
Efficientnet b7 without pretrained -> not working - train loss was easily saturated (on epoch 3~4) and does not change. I also tried multiple optimizer settings with various range of learning rate, but training doses not occur.
Transfer learning from Efficientnet b3 pretrained imagenet weight -> not working - train loss was also easily saturated and dose not progress.

I also tried optimizer settings suggested by Google AI team, but it also didn't work. There may be some critical things that neural network can be trained.

Someone may fix this issue in near future. Thanks for your contribution.

**Comment by qubvel** [comment]
I have disable drop_connect as temporary fix.
You can try it out 
```
$ pip install git+https://github.com/qubvel/efficientnet@fix-drop-connect
```

**Comment by zhoudaxia233** [comment]
> 
> 
> There is some uncertainty about `drop_connect_rate`. It should be much lower at the first blocks. Currently I am waiting answer for issue, and then will fix it.

@qubvel Hi qubvel,
in the original tf implementation, the block number starts from 0
https://github.com/tensorflow/tpu/blob/4cf808e2812ffed44f701f3143d2e7dc7354d40e/models/official/efficientnet/efficientnet_model.py#L396

in your implementation, it starts from 1.
https://github.com/qubvel/efficientnet/blob/989db7d2b148562fbd171f8c91eaf778340ff892/efficientnet/model.py#L223
So the drop_connect_rate for the first blocks are different in yours and the original implementation.

Could this possibly be the reason why it cannot be trained?

**Comment by qubvel** [comment]
I dont think so, may be it is better to try without drop connect. In original implementation it is not still clear if drop connect have been used during training (see issue in original repo).

**Comment by Flock1** [comment]
@qubvel, talking about `drop_connect_rate`, I am getting the following error while trying to save the trained model:

> NameError: name 'drop_connect_rate' is not defined

Now, you suggested installing the library again but I installed it yesterday (one day ago). So what should I do?

**Comment by qubvel** [comment]
Update lib:
```bash
$pip install -U efficientnet
```
