### ISSUE TITLE
Possibly wrong strides?

### ISSUE THREAD

**Issue by mdfwn** [qubvel/efficientnet#12]
Hi, thanks for your Keras implementation! I'm currently looking through the model definition to solidify my understanding of the paper. I've noticed something odd in the parametrisation of the blocks: https://github.com/qubvel/efficientnet/blob/master/efficientnet/params.py#L170 - 
's22' means a stride of [2,2] which means downsampling both image dimensions by half while 's11' means a stride of [1,1] which means no downsampling (this is obvious to you I guess). Your order of strides is: s11 s22 s22 s22 s11 s22 s11 but according to Table 1 in the paper, I think it should be s11 s22 s22 s1 s22 s22 s11. Do you agree or am I wrong somewhere?

**Comment by qubvel** [comment]
Hi @mdfwn 
Look at https://github.com/tensorflow/tpu/issues/383

**Comment by mdfwn** [comment]
I see, thank you very much!
