### ISSUE TITLE
Models pre-trained with NoisyStudent

### ISSUE THREAD

**Issue by rose-jinyang** [qubvel/efficientnet#123]
Hello
How are you?
Thanks for contributing this project.
I've found that you have added noisystudent in your project.
Where can I download the keras models pre-trained with noisystudent from?
Thanks

**Comment by xhlulu** [comment]
They are here: https://github.com/qubvel/efficientnet/releases/tag/v0.0.1

**Comment by rose-jinyang** [comment]
thanks
