### ISSUE TITLE
AttributeError: module 'keras.utils' has no attribute 'generic_utils'

### ISSUE THREAD

**Issue by aadhav-n1** [qubvel/efficientnet#127]
I had installed `efficientnet` (stable version) using `pip` by the following command: `pip install efficientnet`

On importing the library using `import efficientnet.keras as efn`, the following error arises:
```
Traceback (most recent call last)
<ipython-input-6-61d736540c72> in <module>
----> 1 import efficientnet.keras as efn

/opt/conda/lib/python3.7/site-packages/efficientnet/keras.py in <module>
     16 preprocess_input = inject_keras_modules(model.preprocess_input)
     17 
---> 18 init_keras_custom_objects()

/opt/conda/lib/python3.7/site-packages/efficientnet/__init__.py in init_keras_custom_objects()
     69     }
     70 
---> 71     keras.utils.generic_utils.get_custom_objects().update(custom_objects)
     72 
     73 

AttributeError: module 'keras.utils' has no attribute 'generic_utils'
```

**Comment by AdityaR-Bits** [comment]
Go to the line where this issue is happening, then change keras.utils.generic_utils to tensorflow.python.keras.utils.generic_utils. This will solve your issue

**Comment by aadhav-n1** [comment]
@AdityaR-Bits I already have a PR pending above, but the authors/reviewers seem to be inactive, hopefully someone would review and merge the PR.

**Comment by OmarSalah26** [comment]
%env SM_FRAMEWORK=tf.keras 

try this
