### ISSUE TITLE
I want to use `input_shape=(28, 28, 3)`

### ISSUE THREAD

**Issue by minji-o-j** [qubvel/efficientnet#129]
I wrote a code like this
```
model = EfficientNetB3(weights='imagenet', input_shape = (28,28,3), include_top=False)
```
but

```
ValueError: Input size must be at least 32x32; got `input_shape=(28, 28, 3)`
```
this error occured… 

I found some code that used `input_shape = (28,28,3)`,
and in [keras documentation](https://keras.io/api/applications/efficientnet/#efficientnet-b0-to-b7), they explict only: _input_shape: Optional shape tuple, only to be specified if include_top is False. It should have exactly 3 inputs channels._

How can I fix it? 
Or... scale up is the only way to solve the problem?

I use 2 computers and each version is
![image](https://user-images.githubusercontent.com/45448731/91482307-d3166500-e8e0-11ea-80bb-723fd963d441.png)
![image](https://user-images.githubusercontent.com/45448731/91482332-dad60980-e8e0-11ea-925d-575fdf77798e.png)

**Comment by qubvel** [comment]
We have five downsampling operations, so minimum size of input image is 2^5 = 32
