### ISSUE TITLE
ImportError: cannot import name 'load_model'.

### ISSUE THREAD

**Issue by lognat0704** [qubvel/efficientnet#13]
Hi, qubvel. I piped install and trying to import 'load_model, but it got ImportError: cannot import name 'load_model' message. 

I do recheck the whole*.py files but I still can't find any function named  'load_model'. Maybe I should pip installed fom git+https://github.com/qubvel/efficientnet instead of pip install efficientnet directly.

Really appreciate your help.

**Comment by qubvel** [comment]
Hi @lognat0704 
Yes, recent changes are not in PyPI yet, install it from source please.
