### ISSUE TITLE
ValueError: Unknown layer: FixedDropout

### ISSUE THREAD

**Issue by prakashsellathurai** [qubvel/efficientnet#137]
model1 = tf.keras.models.load_model('../input/cassava-leaf-disease-training/efficient_net.h5')

**Comment by RakeshRaj97** [comment]
Did you figure out the solution? I'm also facing the same issue

**Comment by RakeshRaj97** [comment]
Use the below link to download Noisy student weights without top and train the model. 
This solved me the issue of FixedDropout in load_model

https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/image_classification_efficientnet_fine_tuning.ipynb#scrollTo=1rU4e_jLulNs

**Comment by prakashsellathurai** [comment]
Thanks, @RakeshRaj97 It worked Now

**Comment by isahhin** [comment]
I solved it by importing the EfficientNetB4
The problem is that it looks some functions, therefore, we have to import them.

from efficientnet.tfkeras import EfficientNetB4
model = models.load_model('your_model.h5')

**Comment by JasonCZH4** [comment]
@isahhin Thinks,it did work.

**Comment by dinusharuwan** [comment]
I did like this, But I have this error. 
pls any one can help me....

ValueError: Unknown layer: FixedDropout. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

**Comment by elliestath** [comment]
hey, same here. Did you find out how to access FixedDropout layer?
I try to do something like `keras.layers.FixedDropout`
