### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by andewfitting** [qubvel/efficientnet#14]
I found that preprocess_input in official github contain random crop for training. and crop center for eval. However your code has just center crop for eval. 
Is it necessary to do same as original?. or it is just an augmentation process. Now, i'm finetuned all layers but i just use only MEAN RGB and MEAN STD. Good val Acc and test Acc

**Comment by qubvel** [comment]
Hi @andewfitting 
It is up to you what kind of augmentation to use, it is enough to use just MEAN and STD if you are not going to reproduce results mention in paper.
