### ISSUE TITLE
when saving the model structure gets nameerror no drop_connect_rate

### ISSUE THREAD

**Issue by vigneshgig** [qubvel/efficientnet#16]
model_json = model.to_json()

with open("testing.json", "w") as json_file:
    json_file.write(model_json)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-28-a1e9890bfb49> in <module>()
----> 1 model_json = model.to_json()
      2 
      3 
      4 with open("testing.json", "w") as json_file:
      5     json_file.write(model_json)

3 frames
/usr/local/lib/python3.6/dist-packages/efficientnet/layers.py in get_config(self)
     35     def get_config(self):
     36         config = super().get_config()
---> 37         config['drop_connect_rate'] = drop_connect_rate
     38 
     39 

NameError: name 'drop_connect_rate' is not defined

**Comment by andreysher** [comment]
def get_config(self):
        config = super().get_config()
        config['drop_connect_rate'] = self.drop_connect_rate
        return config

**Comment by andreysher** [comment]
> model_json = model.to_json()
> 
> with open("testing.json", "w") as json_file:
> json_file.write(model_json)
> 
> NameError Traceback (most recent call last)
> in ()
> ----> 1 model_json = model.to_json()
> 2
> 3
> 4 with open("testing.json", "w") as json_file:
> 5 json_file.write(model_json)
> 
> 3 frames
> /usr/local/lib/python3.6/dist-packages/efficientnet/layers.py in get_config(self)
> 35 def get_config(self):
> 36 config = super().get_config()
> ---> 37 config['drop_connect_rate'] = drop_connect_rate
> 38
> 39
> 
> NameError: name 'drop_connect_rate' is not defined



> model_json = model.to_json()
> 
> with open("testing.json", "w") as json_file:
> json_file.write(model_json)
> 
> NameError Traceback (most recent call last)
> in ()
> ----> 1 model_json = model.to_json()
> 2
> 3
> 4 with open("testing.json", "w") as json_file:
> 5 json_file.write(model_json)
> 
> 3 frames
> /usr/local/lib/python3.6/dist-packages/efficientnet/layers.py in get_config(self)
> 35 def get_config(self):
> 36 config = super().get_config()
> ---> 37 config['drop_connect_rate'] = drop_connect_rate
> 38
> 39
> 
> NameError: name 'drop_connect_rate' is not defined

    def get_config(self):
        config = super().get_config()
        config['drop_connect_rate'] = self.drop_connect_rate
        return config

**Comment by digital-thinking** [comment]
Same problem here

**Comment by qubvel** [comment]
Use latest version from source

**Comment by digital-thinking** [comment]
I see, thanks for the fix
