### ISSUE TITLE
As backbone for detection task

### ISSUE THREAD

**Issue by changewOw** [qubvel/efficientnet#17]
i had a problem when using your efficiententB3 as backbone for object detection task(previous ResNet50).
while i use ResNet50,batchsize per GPU is 16. But using EfficientNetB3 batchsize per GPU is no more than 12. I also print(model.summary()) to show num of  parameters.ResNet50 is 23,000,000+, EfficientNetB3 is 10,000,000+.
So,obviously,EfficientNetB3's parameters is about half the size of the ResNet50.However,i can only set batchsize to 8 or 12.This make me confused.
My GPU is Tesla P100 -16G mem

**Comment by qubvel** [comment]
Yes, the same for me, I have tried B3 as segmentation backbone, and it takes 2 times more GPU memory than InceptionResnetV2 with 60M params.

**Comment by changewOw** [comment]
Thanks a lot!! 
your souce code is very concise.Maybe this caused by keras ( i guess....)

**Comment by marukitto** [comment]
Any update on this issue? I do have same problem using your segmentation_tools package with efficientnetB3.

**Comment by lukasschmit** [comment]
@changewOw Just curious, what object detection library/model are you using? I'm trying to get efficientnet working with retinanet currently, but resnet has 5 stages whereas efficientnet has 9 stages, so it seems that one can't just drop it in. How did you go about this?

Thanks!

**Comment by mrgloom** [comment]
@changewOw 
Intermediate outputs from layers also stored in memory, so less model weights doesn't mean less memory usage.
https://github.com/DeepScale/SqueezeNet/issues/19#issuecomment-234714578
