### ISSUE TITLE
Loading a model: "Unknown initializer: conv_kernel_initializer"

### ISSUE THREAD

**Issue by stvogel** [qubvel/efficientnet#2]
I trained an EfficientNetB3.
But trying to load the model with keras.load_model(modelfile)
I get this error:
```
File "...python3.6/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown initializer: conv_kernel_initializer
```
What do I miss?

**Comment by qubvel** [comment]
Hi @stvogel 
For now only weights loading is supported.
Crete same model and use model.load_weights(...)
I will fix it in near future.

**Comment by stvogel** [comment]
Great! That worked!
Thanks for your quick response.

**Comment by titu1994** [comment]
@qubvel A simple fix would be to extend the Initializer class in keras.initializers and wrap the conv_initiatializer and dense_initializer code inside `__call__`, and use objects of that class as the initializer for conv and dense respectively.

You would also need to register the two classes as custom objects, which would allow load_model to work without issue.

**Comment by qubvel** [comment]
Hi @titu1994
Thanks for advice, I will do it that way!

**Comment by Razamalik4497** [comment]
> Hi @stvogel
> For now only weights loading is supported.
> Crete same model and use model.load_weights(...)
> I will fix it in near future.

I'm facing same Issue :
**ValueError: Unknown initializer: ConvKernalInitializer. Please ensure this object is passed to the `custom_objects` argument.** 
How can I code this , where should I change ? thank you

**Comment by Razamalik4497** [comment]
> @qubvel A simple fix would be to extend the `Initializer` class in `keras.initializers` and wrap the `conv_initiatializer` and `dense_initializer` code inside `__call__`, and use objects of that class as the initializer for conv and dense respectively.
> 
> You would also need to register the two classes as custom objects, which would allow load_model to work without issue.

Please address me where I get keras.initializer , `conv_initiatializer and dense_initializer ? .  I'm trying to find in Efficientnet files.
