### ISSUE TITLE
Smaller model then EfficientNetB0

### ISSUE THREAD

**Issue by mrgloom** [qubvel/efficientnet#26]
What are recommendations for params for creating smaller then `EfficientNetB0` models for 128x128 input and about 1kk params?

```
# Base EfficientNetB0()
# Total params: 5,330,564
# Trainable params: 5,288,548
# Non-trainable params: 42,016
```

**Comment by krikru** [comment]
According to the core of the [paper](https://arxiv.org/abs/1905.11946), which is compound scaling, you scale the depth with a parameter d=α<sup>ϕ</sup>, the width with a parameter w=β<sup>ϕ</sup>, and the resolution with a parameter r=γ<sup>ϕ</sup>, where ϕ is a parameter that you specify (larger for larger nets and smaller for smaller nets), and α, β and γ are parameters that they find experimentally to be 1.2, 1.1 and 1.15, respectively.

To create a smaller model than `EfficientNetB0`, you simply choose a negative ϕ and scale the depth, width and resolution according to the resulting d, w and r (and then round them to an integer number).
