### ISSUE TITLE
use for object detection

### ISSUE THREAD

**Issue by Borda** [qubvel/efficientnet#4]
Would it be possible to "easily" use this model as a backbone for object detection / instances segmentation as many other popular architectures like ResNet50? Thx

**Comment by qubvel** [comment]
Hi, it should be ok.
I am going to make some experiments with segmentation next week and add it as backbone in qubvel/segmentation_models repo.

**Comment by qubvel** [comment]
#17

**Comment by Lyuba-Rogovaya** [comment]
Hi, does the comment above mean that it is not possible to use your efficientnet as a backbone for segmentation task? If not, could you explain or give a link to how use it as a backbone.

**Comment by qubvel** [comment]
It is possible and already implemented in https://github.com/qubvel/segmentation-models

**Comment by Lyuba-Rogovaya** [comment]
@qubvel  When I try to use efficientnetb0 backbone I get this error: 

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-87689b16bd32> in <module>
      9 input_shape = (256, 1600, 1)
     10 
---> 11 model = Unet(backbone_name=BACKBONE,classes=4, input_shape=(256, 1600, 3), activation='softmax')
     12 model.compile(optim, loss=binary_crossentropy, metrics=[dice_coef])
     13 

/opt/conda/lib/python3.6/site-packages/segmentation_models/utils.py in wrapper(*args, **kwargs)
     29                     kwargs[new_arg] = kwargs[old_arg]
     30 
---> 31             return func(*args, **kwargs)
     32 
     33         return wrapper

/opt/conda/lib/python3.6/site-packages/segmentation_models/unet/model.py in Unet(backbone_name, input_shape, classes, activation, encoder_weights, encoder_freeze, encoder_features, decoder_block_type, decoder_filters, decoder_use_batchnorm, **kwargs)
     61                             input_tensor=None,
     62                             weights=encoder_weights,
---> 63                             include_top=False)
     64 
     65     if encoder_features == 'default':

/opt/conda/lib/python3.6/site-packages/segmentation_models/backbones/__init__.py in get_backbone(name, *args, **kwargs)
     73 
     74 def get_backbone(name, *args, **kwargs):
---> 75     return Classifiers.get_classifier(name)(*args, **kwargs)
     76 
     77 

/opt/conda/lib/python3.6/site-packages/classification_models/__init__.py in get_classifier(cls, name)
     84     @classmethod
     85     def get_classifier(cls, name):
---> 86         return cls._models.get(name)[0]
     87 
     88     @classmethod

TypeError: 'NoneType' object is not subscriptable
`

**Comment by Lyuba-Rogovaya** [comment]
FYI: 
I have installed these packages:

! pip install image-classifiers==1.0.0
! pip install efficientnet==1.0.0
! pip install segmentation-models

**Comment by TolgaBkm** [comment]
I understand that the model can be used for segmentation via segmentation models repo.
But can it be also used for object detection?
