### ISSUE TITLE
load_model('path_to_model') not working

### ISSUE THREAD

**Issue by anandravi24** [qubvel/efficientnet#44]
While trying to load model using load_model(), I am getting this error. ValueError: Unknown initializer: EfficientConv2DKernelInitializer

I followed the steps written on your readme.

![image](https://user-images.githubusercontent.com/30256736/61908587-e0467080-aee4-11e9-8393-d5c9c5b28a8c.png)

**Comment by anandravi24** [comment]
While trying to load model using load_model(), I am getting this error. ValueError: Unknown initializer: EfficientConv2DKernelInitializer

I followed the steps written on your readme.

![image](https://user-images.githubusercontent.com/30256736/61908587-e0467080-aee4-11e9-8393-d5c9c5b28a8c.png)

**Comment by qubvel** [comment]
If you update the lib a few days ago installing it from source, please rool back, they are not compatible. 
Try `pip install -U efficientnet==0.0.4` and try to load model again.

**Comment by anandravi24** [comment]
Thank you, it worked. I uninstalled the latest version and installed it again using the command you mentioned above.

**Comment by Eton** [comment]
Hi,

I was installed efficientnet==0.0.4, but got same error.

tensorflow 1.12.0
keras 2.2.4

please help , thanks

**Comment by pranavdogra7** [comment]
> Hi,
> 
> I was installed efficientnet==0.0.4, but got same error.
> 
> tensorflow 1.12.0
> keras 2.2.4
> 
> please help , thanks

@Eton try this
from keras.models import load_model
import efficientnet
_ = efficientnet.model.EfficientNetB5() #which ever architecture you trained on, I used B5
model = load_model('model/model_weights_efficient.h5')

**Comment by emoen** [comment]
What has happend to version 0.0.4?

When I run RUN pip install -U git+https://github.com/qubvel/efficientnet==0.0.4
i get:
ERROR: Command errored out with exit status 128: git clone -q https://github.com/qubvel/efficientnet==0.0.4 'C:\Users\<..>\AppData\Local\Temp\pip-req-build-l4nz2h8r' Check the logs for full command output.

**Comment by emoen** [comment]
I think the command should be: pip install -U git+https://github.com/qubvel/efficientnet@v0.0.4
