### ISSUE TITLE
how to change efficientnet model?

### ISSUE THREAD

**Issue by shubhaminnani** [qubvel/efficientnet#54]
@qubvel I want to change the downsampling factor from 32 to 16 of last layer keeping everything else same? how can I change it? Thanks in advance! :)

**Comment by qubvel** [comment]
You can truncate the model or change stride in some of convolutions from 2 to 1.

**Comment by shubhaminnani** [comment]
but the code is written with blocks how to change the further model?

**Comment by qubvel** [comment]
Fork and change strides here for example https://github.com/qubvel/efficientnet/blob/48e36b49f36e7dadfe59b7fd76a6f0a1d2e6c0df/efficientnet/model.py#L377

**Comment by shubhaminnani** [comment]
Thank you!!
