### ISSUE TITLE
Is there any possible way to convert model to tflite?

### ISSUE THREAD

**Issue by cruigo93** [qubvel/efficientnet#57]
Currently, I am loading the model and than trying to convert it to tflite. I've used just EffNet from 0.0.4 and keras/tfkeras from pre version, but issues occurred

ValueError: Unknown activation function:swish

**Comment by qubvel** [comment]
Hi you could try to replace `tf.nn.swish` with `x * sigmoid(x)` (its the same). Just fork repo and modify swish function in model.py.

**Comment by cruigo93** [comment]
Thank you for reply.

**Comment by bhavitvyamalik** [comment]
Hi!
I forked your repository and changed return type of activation function get_swish() to x*sigmoid(x) but it is still giving me the same error. Have you used swish activation somewhere else also?

**Comment by shaunster0** [comment]
I got the same problem ... its weird, it trained on GCP and did inference fine on my laptop but when I uploaded model to AWS it gave this error, even when I set the TF version to the one I've been using

**ValueError: Unknown activation function:swish**

**Comment by cruigo93** [comment]
@shaunster0 Did you tried as @qubvel pointed, replace swish to x * sigmoid(x)

**Comment by shaunster0** [comment]
@cruigo93 its too late now I've already done training, i guess i'll have to re-train doing as he says.
Did it work for u?

**Comment by sklipnoty** [comment]
This is very annoying, please change the base repo to reflect the suggested change. 

Or do another work-around suggestion? Re-training is not always an option.

**Comment by qubvel** [comment]
You dont need to retrain, just change swish and load previous weights.

**Comment by shaunster0** [comment]
thanks Pavel, and thanks for ur projects, they’re fantastic!

**Comment by shaunster0** [comment]
I did as Pavel said, still getting the error trying inference in cloud (but training ran fine again)

File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 306, in get
2019-11-20 14:33:54return deserialize(identifier)
2019-11-20 14:33:54File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 297, in deserialize
2019-11-20 14:33:54printable_module_name='activation function')
2019-11-20 14:33:54File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 211, in deserialize_keras_object
2019-11-20 14:33:54raise ValueError('Unknown ' + printable_module_name + ':' + object_name)
2019-11-20 14:33:54ValueError: Unknown activation function:swish
2019-11-20 14:33:54['Error running detect_showers. Error: Unknown activation function:swish.']

ie. still cant find swish, even when I changed to x * sigmoid(x)

**Comment by bhavitvyamalik** [comment]
Can you show the code you've used to convert your file to TFLite?

**Comment by Samjith888** [comment]
> You dont need to retrain, just change swish and load previous weights.

just replaced the line in model.py inside efficientnet. But still getting the same error


def get_swish(**kwargs):
    backend, layers, models, keras_utils = get_submodules_from_kwargs(kwargs)

```
    def swish(x):
        """Swish activation function: x * sigmoid(x).
        Reference: [Searching for Activation Functions](https://arxiv.org/abs/1710.05941)
        """

        if backend.backend() == 'tensorflow':
            try:
                # The native TF implementation has a more
                # memory-efficient gradient implementation
                return backend.x * sigmoid(x)
            except AttributeError:
                pass

        return x * backend.sigmoid(x)

    return swish
```

**Comment by fuaiguo** [comment]
@shaunster0 @sklipnoty 
Hi, have you solved this error? I have changed the swish to x*sigmoid , but have the same error, still cant find swish. Do you have any good methods

**Comment by shaunster0** [comment]
I eventually got it working ... I was missing an import statement for quubvel’s projects ... check carefully the import statements needed for Segmentation Models and EfficientNet ... I can’t remember exactly, but I had one import line missing, which caused this.

Shaun
