### ISSUE TITLE
Undocumented but needed function argument 'backend'

### ISSUE THREAD

**Issue by krikru** [qubvel/efficientnet#59]
I'm now getting the error message

```
AttributeError: 'NoneType' object has no attribute 'image_data_format'
```

on [this line](https://github.com/qubvel/efficientnet/blob/master/efficientnet/model.py#L362). It appears that a `backend` argument needs to be provided when creating EfficientNet through any of the `EfficientNetB*` functions, but this is an undocumented argument as far as I can see.

What value should be provided for it?

**Comment by qubvel** [comment]
README use efficientnet.keras/tf.keras submodules, this modules inserts in kwargs.

**Comment by krikru** [comment]
Thanks; changing from the `efficientnet.model` submodule to the `efficientnet.keras` submodule did the trick.
