### ISSUE TITLE
[tf 2.0] efficientnetB7 - Large dropout rate

### ISSUE THREAD

**Issue by kielnino** [qubvel/efficientnet#60]
Thank you so much for your great work on this and the segmentation_models!

Wenn I use the efficientnetB7 with tensorflow 2.0 (2.0.0-beta1) it prints:

> Large dropout rate: 0.5625 (>0.5). In TensorFlow 2.x, dropout() uses dropout rate instead of keep_prob. Please ensure that this is intended

Is this already handled?

**Comment by JeremyAlain** [comment]
I am wondering the same...

**Comment by anh-ng** [comment]
I think it already handled correctly. See https://github.com/qubvel/efficientnet/blob/91366f5101270f505c982cfa125fefc982986bf1/efficientnet/model.py#L441
