### ISSUE TITLE
tensorflow 2.0.0 doesn't work in efficientnet

### ISSUE THREAD

**Issue by Dicksonchin93** [qubvel/efficientnet#63]
this is the traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-0f7ee82794b3> in <module>
      1 import efficientnet
      2 
----> 3 model = efficientnet.EfficientNetB3(weights=None)

~/anaconda3/envs/py36/lib/python3.7/site-packages/efficientnet/model.py in EfficientNetB3(include_top, input_shape, input_tensor, weights, classes, pooling)
    441         weights=weights,
    442         classes=classes,
--> 443         pooling=pooling,
    444     )
    445 

~/anaconda3/envs/py36/lib/python3.7/site-packages/efficientnet/model.py in _get_model_by_name(model_name, input_shape, input_tensor, include_top, weights, classes, pooling)
    367         input_tensor=input_tensor,
    368         include_top=include_top,
--> 369         pooling=pooling,
    370     )
    371 

~/anaconda3/envs/py36/lib/python3.7/site-packages/efficientnet/model.py in EfficientNet(input_shape, block_args_list, global_params, input_tensor, include_top, pooling)
    214     # Stem part
    215     if input_tensor is None:
--> 216         inputs = KL.Input(shape=input_shape)
    217     else:
    218         if not K.is_keras_tensor(input_tensor):

~/anaconda3/envs/py36/lib/python3.7/site-packages/keras/engine/input_layer.py in Input(shape, batch_shape, name, dtype, sparse, tensor)
    176                              name=name, dtype=dtype,
    177                              sparse=sparse,
--> 178                              input_tensor=tensor)
    179     # Return tensor including _keras_shape and _keras_history.
    180     # Note that in this case train_output and test_output are the same pointer.

~/anaconda3/envs/py36/lib/python3.7/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name + '` call to the ' +
     90                               'Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/anaconda3/envs/py36/lib/python3.7/site-packages/keras/engine/input_layer.py in __init__(self, input_shape, batch_size, batch_input_shape, dtype, input_tensor, sparse, name)
     37         if not name:
     38             prefix = 'input'
---> 39             name = prefix + '_' + str(K.get_uid(prefix))
     40         super(InputLayer, self).__init__(dtype=dtype, name=name)
     41 

~/anaconda3/envs/py36/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py in get_uid(prefix)
     72     """
     73     global _GRAPH_UID_DICTS
---> 74     graph = tf.get_default_graph()
     75     if graph not in _GRAPH_UID_DICTS:
     76         _GRAPH_UID_DICTS[graph] = defaultdict(int)

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

maybe lets make an update to requirements.txt?

**Comment by qubvel** [comment]
Hi, please update library to 1.* verison and read README file, thanks.

**Comment by Borda** [comment]
Do you plan to upgrade in future on TF2.x?

**Comment by qubvel** [comment]
@Borda 
Does not see any limitations, if TF2 support tf.keras it should work. If you have any troubles please report an error stack trace.

**Comment by Borda** [comment]
When I was working on YOLO detector using Keras I had some issue with newly release Keras 2.2.5 which was falling because of
```
AttributeError: module 'keras.backend' has no attribute 'control_flow_ops'
```
