### ISSUE TITLE
Batch size dramatically drop when training EfficientNetB4 comparing with InceptionV3

### ISSUE THREAD

**Issue by yunkchen** [qubvel/efficientnet#64]
[Environment] GeForce RTX 2080 11GB
The max batch size dramatically drop to 8 in training EfficientNetB4 with 1 GPU, while the bacth size is 64 in training InceptionV3. 

- EfficientNetB4 vs InceptionV3
- Params 19M vs 24M
- Input size 380 vs 299
- Max Batch size 8 vs 64

Thanks for any help.

**Comment by qubvel** [comment]
Hi, yes this is not so memory efficient due to `swish` activation
