### ISSUE TITLE
how to train a new model using my own dataset?

### ISSUE THREAD

**Issue by JacobLee121** [qubvel/efficientnet#65]

**Comment by qubvel** [comment]
Hi, the question is too broad. Train it as any other classification model. For more specific details read original paper.

**Comment by Borda** [comment]
I think that the question is such: Do you have or do you plan to add a script for training this network on custom dataset? Thx

**Comment by JacobLee121** [comment]
> I think that the question is such: Do you have or do you plan to add a script for training this network on custom dataset? Thx

yes, I want to change the structure of the efficientnet and train a new model on my own dataset

**Comment by Borda** [comment]
see also https://github.com/qubvel/efficientnet/issues/22#issuecomment-503984613 and #1 :imp:

**Comment by qubvel** [comment]
There is no plan to implement training script, at least not in near future and not in this repo.
