### ISSUE TITLE
Ability to use tensorflow.keras instead of regular keras?

### ISSUE THREAD

**Issue by vbogach** [qubvel/efficientnet#7]
Could we choose tf.keras instead of keras? I tried saving the model and loading it via tf.keras load_model to convert it to tf.keras, but it gives me the same error as #2.

**Comment by qubvel** [comment]
Hi @vbogach 
Take a look at this fork https://github.com/mattiavarile/efficientnet or official tensorflow repo (README)

**Comment by qubvel** [comment]
Also #18
