### ISSUE TITLE
Problem in converting model to TFLite

### ISSUE THREAD

**Issue by bhavitvyamalik** [qubvel/efficientnet#77]
I was trying to convert my EfficientNet model to TFLite:

`converter = tf.lite.TFLiteConverter.from_keras_model_file('effNetB3.h5',custom_objects={'swish': Swish(swish)})` 
`tfmodel = converter.convert()` 
`open ("effNetB3.tflite" , "wb") .write(tfmodel)`

 It gave me the following error:
`ValueError: Unknown layer: FixedDropout`

**Comment by qubvel** [comment]
Import efficientnet.keras or efficientnet.tfkeras before loading h5 file.

**Comment by bhavitvyamalik** [comment]
Changed my code to this still facing the same problem

`import efficientnet.keras`

`converter = tf.lite.TFLiteConverter.from_keras_model_file('effNetB3.h5', custom_objects={'swish': Swish(swish)}) `
`tfmodel = converter.convert() `
`open ("effNetB3.tflite" , "wb") .write(tfmodel)`

Now it is converting without any issues. Thank you!

**Comment by qubvel** [comment]
Could you just load_model?

**Comment by bhavitvyamalik** [comment]
Yes, able to do that
`from keras.models import load_model`
`model = load_model('effNetB3.h5',custom_objects={'swish': Swish(swish)})`

How to send it to TFLiteConverter as it is expecting str, bytes or os.PathLike object, not Model

**Comment by qubvel** [comment]
I am not working with tf lite, so dont have an answer for you. If model deserialize correctly it is a problem of coverter. 
One workaround I can suggest:
Fork repo, remove dropout layer (it is not used during inference stage), load weights from you trained model (should be ok, because droupout layer does not have weights), validate that both models produce same outputs for same inputs, try to convert new model.

**Comment by bhavitvyamalik** [comment]
Also, I remember doing this initially to convert my model and surprisingly it did convert. When I tried doing it next time it started throwing error.

`from keras.models import load_model`
`import efficientnet.keras`

`model = load_model('effNetB3.h5',custom_objects={'swish': Swish(swish)})`
`converter = tf.lite.TFLiteConverter.from_keras_model_file('effNetB3.h5')`
`tfmodel = converter.convert()`
`open ("effNetB3.tflite" , "wb") .write(tfmodel)`

**Comment by 2696120622** [comment]
@bhavitvyamalik 
Have you resolved the problem and converted to tflite successfully?
If sure, can you share your code for converting and inference?

**Comment by murdav** [comment]
It is not strictly related to the conversion problem, but I had the same issue on a model saved (`ValueError FixedDropout`). It is successfully loaded doing:

```
import efficientnet.tfkeras
from tensorflow.keras.models import load_model

model = load_model('path/to/model.h5')
```
