### ISSUE TITLE
Importing keras backend fails when using preprocess_input

### ISSUE THREAD

**Issue by rstml** [qubvel/efficientnet#78]
I'm trying to use `efficientnet.model.preprocess_input` as `ImageDataGenerator(preprocessing_function=preprocess_input, ...)`. However, getting following error:

```
~/.virtualenvs/venv1/lib/python3.7/site-packages/keras_applications/imagenet_utils.py in preprocess_input(x, data_format, mode, **kwargs)
    184 
    185     if data_format is None:
--> 186         data_format = backend.image_data_format()
    187     if data_format not in {'channels_first', 'channels_last'}:
    188         raise ValueError('Unknown data_format ' + str(data_format))

AttributeError: 'NoneType' object has no attribute 'image_data_format'
```

Symptoms look very similar to keras-team/keras-applications#54 and it seems that solution can be also similar to https://github.com/keras-team/keras-applications/issues/54#issuecomment-445129490_ , i.e. replacing `keras_applications` with `keras.applications` here:
https://github.com/qubvel/efficientnet/blob/91366f5101270f505c982cfa125fefc982986bf1/efficientnet/model.py#L39

**Comment by qubvel** [comment]
Hi, do not use any imports from model.py
Look at readme, all you need is located under following backend (keras/tfkeras).

**Comment by rstml** [comment]
Ah, right... Not sure why I missed it. This works:
```
from efficientnet.keras import preprocess_input
```
